version: '2.1'
services:
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  eurekaserver:
    extends:
      file: ../common/docker-compose.yml
      service: eurekaserver
  authserver:
    extends:
      file: ../common/docker-compose.yml
      service: authserver
  assetsservice:
    image: kayoubi/assets-service:3.3
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      configserver:
        condition: service_healthy
      database-dev:
        condition: service_started
  gatewayserver:
    image: kayoubi/gateway-server:3.3
    ports:
      - "8787:8787"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_started
  organizationservice1:
    image: kayoubi/organization-service:3.3
    ports:
      - "8181:8181"
    depends_on:
      configserver:
        condition: service_healthy
      database-dev:
        condition: service_started
      eurekaserver:
        condition: service_started
#      kafkaserver:
#        condition: service_started
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  organizationservice2:
    image: kayoubi/organization-service:3.3
    ports:
      - "8182:8181"
    depends_on:
      configserver:
        condition: service_healthy
      database-dev:
        condition: service_started
      eurekaserver:
        condition: service_started
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  database-dev:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_DB:       "eagle_eye_dev"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafkaserver:
    image: wurstmeister/kafka
    ports:
#      - 2181:2181
      - 9092:9092
    environment:
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_LISTENERS=PLAINTEXT://:9092"
      - 'HOSTNAME_COMMAND: "echo $$(hostname)"'
      - 'KAFKA_ADVERTISED_PORT: 9092'
      - 'KAFKA_PORT: 9092'
      - "BROKER_ID_COMMAND: \"docker inspect --format '{{ .Name }}' $$(hostname) | awk -F_ '{ printf $$NF }'\""
  redis:
    extends:
      file: ../common/docker-compose.yml
      service: redis
