server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/conf/assetservice
  profiles:
    active: native

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          repos: