spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "false"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    platform: "postgres"
  database:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://database:5432/eagle_eye_local"
    username: "postgres"
    password: "p0stgr@s"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

