version: '2.1'
services:
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  assetsservice:
    image: kayoubi/assets-service:chapter-3
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      configserver:
        condition: service_healthy
      database-dev:
        condition: service_started
  database-dev:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_DB:       "eagle_eye_dev"