server:
  port: 8888

spring:
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/conf/assetservice
        git:
          uri: https://github.com/kayoubi/harv-conf-server
          searchPaths: assetservice, organizationservice
        encrypt:
          enabled: true
#  profiles:
#    active: native

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          repos: